### ISSUE TITLE
 Update `istio-operators`

### ISSUE THREAD

**Issue by misohu** [canonical/istio-operators#413]
### Context

Each charm has a set of manifest files that have to be upgraded to their target version. The process of upgrading manifest files usually means going to the component’s upstream repository, comparing the charm’s manifest against the one in the repository and adding the missing bits in the charm’s manifest.

### What needs to get done

https://docs.google.com/document/d/1a4obWw98U_Ndx-ZKRoojLf4Cym8tFb_2S7dq5dtRQqs/edit?pli=1#heading=h.jt5e3qx0jypg

### Definition of Done

1. Manifests are updated

**Comment by DnPlas** [comment]
I will be using this task to track all of the required changes for this repository. The versions that we want to start supporting are:
* 1.18.7
* 1.19.10
* 1.20.6
* 1.21.2
* 1.22.0

**Comment by DnPlas** [comment]
### TODO

- [ ] Request tracks in Charmhub for all the new versions we are supporting
- [ ] Cut the branches for each version we are now supporting
- [ ] The above should ideally happen after merging #401 because we want that change to be included in all the versions we recently introduced.

**Comment by DnPlas** [comment]
#### Important note about upgrades

Running an upgrade from istio 1.17 -> 1.20 is possible in Kubernetes =<1.25. Istio 1.21 will not allow any upgrade any further because of the following:

```
Error [IST0142] (Cluster) The Kubernetes Version "v1.25.16" is lower than the minimum version: 1.26
Error: Issues found when checking the cluster. Istio may not be safe to install or upgrade.
See https://istio.io/v1.21/docs/reference/config/analysis for more information about causes and resolutions.
```

We must be extra careful with the upgrade path for istio.

**Comment by DnPlas** [comment]
All branches are now in place, closing this.
